
export interface Title{
  id: number;
  name: string;
  type: string;
  tmdb_vote_average: number;
  release_date: string;
  year: number;
  description: string;
  genre: string;
  tagline: string;
  poster: string;
  backdrop: string;
  runtime: number;
  trailer: string;
  budget: number;
  revenue: number;
  views: number;
  popularity: number;
  imdb_id: string;
  tmdb_id: number;
  season_count: number;
  fully_synced: number;
  allow_update: number;
  created_at: string;
  updated_at: string;
  language: string;
  country: string;
  original_title: string;
  affiliate_link: string;
  tmdb_vote_count: number;
  certification: string;
  episode_count: number;
  series_ended: number;
  is_series: number;
  local_vote_average: number;
  show_videos: number;
  adult: number;
  local_vote_count: number
}